[phases.setup]
nixPkgs = ['php83', 'php83Extensions.pdo', 'php83Extensions.pdo_sqlite', 'php83Extensions.sqlite3', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.fileinfo', 'php83Extensions.tokenizer', 'php83Extensions.dom']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'touch database/database.sqlite',
    'php artisan migrate --force --seed'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
